phuria_demo_get_clinics_data:
    pattern: /clinics
    defaults: { _controller: PhuriaDemoBundle:Demo:clinics }
    
phuria_demo_get_procedures_data:
    pattern: /porcedures
    defaults: {_controller: PhuriaDemoBundle:Demo:procedures }

phuria_demo_homepage:
    pattern:  /{id}
    defaults: { _controller: PhuriaDemoBundle:Demo:index, id: 0 }