phuria_demo_get_procedures_data:
    pattern: /procedures
    defaults: {_controller: PhuriaDemoBundle:Demo:procedures }
    
phuria_demo_get_procedures_init_data:
    pattern: /procedures/init/{doctorId}
    defaults: {_controller: PhuriaDemoBundle:Demo:initProcedures }

phuria_demo_homepage:
    pattern:  /{id}
    defaults: { _controller: PhuriaDemoBundle:Demo:index, id: 0 }