Phuria\DemoBundle\Entity\Procedure:
    type: entity
    repositoryClass: Phuria\DemoBundle\Repository\ProcedureRepository
    manyToMany:
        doctors:
            targetEntity: Doctor
            mappedBy: procedures
    table: procedure_
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        
        